spring.application.name=AgenciaSpring
spring.graphql.graphiql.enabled=true
server.port=${PORT:8082}

# Conexión a Base de Datos en Railway (Postgres - Tokaido)
spring.datasource.url=jdbc:postgresql://shinkansen.proxy.rlwy.net:12293/railway?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=EjMRBenmowhuKkEWdMJpNeyLeZnidzLN
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optimización de Conexiones HikariCP para Railway (Evita Caídas y Timeouts)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=580000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1

# URL del nodo de Blockchain desplegado en Railway
blockchain.node.url=https://blockchain-agencia-production.up.railway.app

# Configuración CORS para Spring GraphQL
spring.graphql.cors.allowed-origin-patterns=*
spring.graphql.cors.allowed-headers=*
spring.graphql.cors.allowed-methods=GET,POST,OPTIONS
spring.graphql.cors.allow-credentials=true
