spring.application.name=AgenciaSpring
spring.graphql.graphiql.enabled=true
server.port=${PORT:8082}

# Conexión a Base de Datos en Railway (Postgres-kFbE)
spring.datasource.url=jdbc:postgresql://switchback.proxy.rlwy.net:16638/railway?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=postgres
spring.datasource.password=BXNSpZCyHLcDPYBcaKizHhwwZydMKknB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# URL del nodo de Blockchain desplegado en Railway
blockchain.node.url=https://blockchain-agencia-production.up.railway.app

# Configuración CORS para Spring GraphQL
spring.graphql.cors.allowed-origin-patterns=*
spring.graphql.cors.allowed-headers=*
spring.graphql.cors.allowed-methods=GET,POST,OPTIONS
spring.graphql.cors.allow-credentials=true
