spring.application.name=AgenciaSpring
spring.graphql.graphiql.enabled=true
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/MSSpring
spring.datasource.username=postgres
spring.datasource.password=12731031
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Blockchain Node URL
blockchain.node.url=http://localhost:3001
